apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tomcat-deployment.yaml
  - tomcat-service.yaml
images:
  - name: 554304941374.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic_btc
    newTag: c6d957903525e00ff3597e70f53e0272768ecf01
