apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tomcat-deployment.yaml
  - tomcat-service.yaml
images:
  - name: 554304941374.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic_btc
    newTag: 16fb6ac1e1f4b2cc39217d66a6b8b743db11feab
