apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tomcat-deployment.yaml
  - tomcat-service.yaml
images:
  - name: 554304941374.dkr.ecr.ap-northeast-2.amazonaws.com/petclinic_btc
    newTag: 15c54764124a5e84680e2cb11487044254a3fec1
