name: Build, Push to ECR and Update GitOps Manifest

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: petclinic_btc
  ECR_URI: 554304941374.dkr.ecr.ap-northeast-2.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_REPO: zeroweak90/was-service
  MANIFEST_PATH: base/kustomization.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write        # OIDC 인증
      contents: write        # GitOps repo에 push 가능하게

    steps:
    - name: Checkout application source
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::554304941374:role/eks-github-test2
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_URI/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Checkout GitOps repo
      uses: actions/checkout@v3
      with:
        repository: ${{ env.GITOPS_REPO }}
        token: ${{ secrets.GH_PAT }}   # GitHub PAT 필요 (repo 권한)
        path: gitops

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Update image tag in kustomization.yaml
      run: |
        cd gitops
        yq -i '.images[0].newTag = "${{ env.IMAGE_TAG }}"' ${{ env.MANIFEST_PATH }}
        git config user.name  "github-actions"
        git config user.email "actions@github.com"
        git commit -am "ci: update image tag to ${{ env.IMAGE_TAG }}"
        git push origin main
